name: 'Update Files'
description: 'Update Json Files Based on Issue Input'
inputs:
  github-token:
    description: 'GitHub token for repo'
    required: true
  file-path:
    description: 'Path of the file to update'
    required: true
  lable:
    description: 'lable which is used to update the file'
    required: true
    default: 'invite me to the organisation'
  file-content:
    description: 'Keys of JSON file to update'
    required: true
    default: ['Name', 'Roll', 'Email', 'Github username']
runs:
  using: 'node16'
  main: 'index.js'
